Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DAL.Entities;
using Web.Models.Entity;
using Web.Models.Model;
using Web.Service.Interface;

namespace Web.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly IPagingHandler<Post> _pagingHandler;
        public CategoryController(DbContext dbContext, ICategoryService categoryService, IPagingHandler<Post> pagingHandler) : base(dbContext)
        {
            this._categoryService = categoryService;
            _pagingHandler = pagingHandler;
        }

        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CategoryModel model)
        {
            var newCategory= Mapper.Map(model, new Category());
            _categoryService.Create(newCategory);
            return View();
        }

        [ChildActionOnly]
        public ActionResult GetCategoies()
        {
            var categoies = _categoryService.GetAll(c=>new CategoryModel() {Name = c.Name,Id = c.Id,CountPost = c.Posts.Count});
            return PartialView("GetCategoies",categoies);
        }

        public ActionResult GetPostByCategory(int id,int ?page)
        {
            _pagingHandler.PageIndex = page ?? 1;
            var postList = _pagingHandler.GetPagingList(c=>c.CategoryId==id,c => new PostModel()
            {
                Title = c.Title,
                DateTime = c.DateTime,
                ShortDescription = c.ShortDescription,
                FullName = c.User.FirstName + " " + c.User.LastName,
                Id = c.Id
            }, c => c.DateTime, ListSortDirection.Descending).ToList();

            var pagingModel = new PagingModel()
            {
                HasNextPage = _pagingHandler.HasNextPage,
                HasPreviousPage = _pagingHandler.HasPreviousPage,
                PageIndex = _pagingHandler.PageIndex,
                IsFirstPage = _pagingHandler.IsFirstPage,
                IsLastPage = _pagingHandler.IsLastPage,
                PageCount = _pagingHandler.PageCount,
                PageNumber = _pagingHandler.PageNumber,
                PageSize = _pagingHandler.PageSize
            };

            var model = new Tuple<List<PostModel>, PagingModel>(postList, pagingModel);
            return View("_ListPost", model);
        }
    }
}

Web/Controllers/CommentController.cs
using System.Data.Entity;
using System.Web.Mvc;
using Web.Service.Interface;

namespace Web.Controllers
{
    public class CommentController : BaseController
    {
        private ICommentService _commentService;
        public CommentController(DbContext dbContext, ICommentService commentService) : base(dbContext)
        {
            _commentService = commentService;
        }

        public ActionResult GetRecentComments()
        {
            return PartialView("_GetRecentComments");
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - BlogForMe</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Post/List">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post,new {id= "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                }


                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li> <a href="#">Hello! @User.Identity.Name</a> </li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log Out</a></li>
                    }
                    else
                    {
                        <li><a href="/Account/Register"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="/Account/Login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    }
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<!--container-->
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <h1 class="page-header">
                    @ViewBag.Title
                </h1>
                @RenderBody()

            </div>
            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Blog Search Well -->

                @Html.Partial("_Search")

                <!-- Blog Categories Well -->

                @Html.Action("GetCategoies","Category")
                <!-- Side Widget Well -->

                @Html.Action("GetRecentComments","Comment")

              
            </div>
        </div>
        <!-- /.row -->
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; BlogForMe 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>
    </div>
    <!-- /.container -->

     
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Shared/_ListPost.cshtml
@using Web.Models.Model
@using Web.Utility
@model Tuple<List<PostModel>, PagingModel>


@foreach (var post in Model.Item1)
{
    <h2>
        <a href="#">@post.Title</a>
    </h2>
    <p class="lead">
        by <a href="/post/list">@post.FullName</a>
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on @post.DateTime.ToShortTimeString()</p>
    <hr>
        //<img class="img-responsive" src="@post.Image" alt="">
    <hr>
    <p>@post.ShortDescription</p>
    <a class="btn btn-primary" href="/post/detail/@post.Id">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
    <hr>
}
    <!-- Pager -->
@*<ul class="pager">
    <li class="previous">
        <a href="#">&larr; Older</a>
    </li>
    <li class="next">
        <a href="#">Newer &rarr;</a>
    </li>
</ul>*@
@Html.PagingHelper(Model.Item2.PageIndex, Model.Item2)

Web/Views/Shared/_Search.cshtml
@model dynamic
<div class="well">
    <h4>Blog Search</h4>
    <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
            <button class="btn btn-default" type="button">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div>
    <!-- /.input-group -->
</div>